[build]
  command = "npm run build"  # Specify your build command if different
  publish = "build"  # Specify the directory to publish
  node_version = "16"  # Specify the Node.js version you want to use
